[package]
name = "play_web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
chrono = { version = "0.4.26", features = ["serde"] }
dashmap = "5.5.0"
env_logger = "0.10.0"
serde_json = "1.0.103"
uuid = { version = "1.4.1", features = ["v4"] }
